-- Canvas - Path1
-- Course
select c.COURSE_ID, c.COURSE_NAME, c.COURSE_TITLE, c.CREDIT_HOURS, c.ACTIVE_FLG, 
       c.MAX_ENROLLMENT, c.MIN_ENROLLMENT, c.PROVIDER_ID, tt.term_type_id
from COURSE c
left join term_type tt on c.provider_id = tt.provider_id;

-- Canvas_course
select CANVAS_COURSE_ID, COURSE_ID, CANVAS_COURSE_TITLE, TERM_ID, IS_FULL 
from CANVAS_COURSE;

-- Canvas_course_Enrollment
select CANVAS_COURSE_ENROLLMENT_ID, CANVAS_COURSE_ID, PERSON_ID, TERM_ID, COURSE_ID, 
       GRADE, GRADE_PERCENT, TOTAL_TIME, NUM_SUBMISSIONS, CREATED_DATE, LAST_LOGIN_DATE
from CANVAS_COURSE_ENROLLMENT;

-- Canvas_transcript
select CANVAS_TRANSCRIPT_ID, CANVAS_COURSE_ID, PERSON_ID, GRADE, CREATED_DATE, MODIFIED_DATE 
from CANVAS_TRANSCRIPT;

-- Path2
-- Course
select COURSE_ID, COURSE_NAME, COURSE_TITLE, CREDIT_HOURS, ACTIVE_FLG, MAX_ENROLLMENT, 
       MIN_ENROLLMENT, PROVIDER_ID, TERM_TYPE_ID, BASE_PRICE, BASE_UNITS  
from COURSE;

-- Canvas_course
select CANVAS_COURSE_ID, COURSE_ID, CANVAS_COURSE_TITLE, TERM_ID, IS_FULL 
from CANVAS_COURSE;

-- Canvas_course_Enrollment
select CANVAS_COURSE_ENROLLMENT_ID, CANVAS_COURSE_ID, PERSON_ID, TERM_ID, COURSE_ID, 
       GRADE, GRADE_PERCENT, TOTAL_TIME, NUM_SUBMISSIONS, CREATED_DATE, LAST_LOGIN_DATE
from CANVAS_COURSE_ENROLLMENT;

-- Canvas_transcript
select CANVAS_TRANSCRIPT_ID, CANVAS_COURSE_ID, PERSON_ID, GRADE, CREATED_DATE, MODIFIED_DATE 
from CANVAS_TRANSCRIPT;