-- Canvas_course_Enrollment

select PERSON_ID, CANVAS_COURSE_ID, CANVAS_COURSE_ENROLLMENT_ID, TERM_ID, COURSE_ID, 
       
       GRADE, GRADE_PERCENT, TOTAL_TIME, NUM_SUBMISSIONS, CREATED_DATE, LAST_LOGIN_DATE

from CANVAS_COURSE_ENROLLMENT;
