-- Course
SELECT 
    COURSE_ID
    ,COURSE_NAME
    ,COURSE_TITLE
    ,CREDIT_HOURS
    ,ACTIVE_FLG
    ,MAX_ENROLLMENT
    ,MIN_ENROLLMENT
    ,PROVIDER_ID
    ,TERM_TYPE_ID
    ,BASE_PRICE
    ,BASE_UNITS  
    
FROM COURSE;