SELECT
     s.PERSON_ID
    ,s.MEMBERSHIP_ID
    ,s.LDS_ACCOUNT
    ,cp.CMIS_ID
    ,e.EMPLOYEE_ID

FROM STUDENT s
    LEFT JOIN CMIS_PERSONS cp 
        ON cp.MRN = s.MEMBERSHIP_ID
    LEFT JOIN EMPLOYEE e 
        ON e.LDS_ACCOUNT_ID = s.LDS_ACCOUNT;