SELECT 
    PERSON_ID
  , d2l_COURSE_ID
  , d2l_COURSE_ENROLLMENT_ID
  , TERM_ID
  , COURSE_ID
  , GRADE
  , GRADE_PERCENT
  , TOTAL_TIME
  , NUM_SUBMISSIONS 
  , CREATED_DATE
  , LAST_LOGIN_DATE

FROM d2l_COURSE_ENROLLMENT;

